<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0-android</TargetFrameworks>

    <OutputType>Exe</OutputType>
    <RootNamespace>PhoneSnmpAgent</RootNamespace>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- Android compatibility -->
    <SupportedOSPlatformVersion>21.0</SupportedOSPlatformVersion>
    <TargetPlatformMinVersion>21.0</TargetPlatformMinVersion>

    <!-- Android 14 (API 34) -->
    <AndroidCompileSdkVersion>34</AndroidCompileSdkVersion>
    <AndroidTargetSdkVersion>34</AndroidTargetSdkVersion>
    <AndroidSdkVersion>34</AndroidSdkVersion>
    <AndroidUseLatestPlatformSdk>true</AndroidUseLatestPlatformSdk>

    <!-- App Info -->
    <ApplicationTitle>PhoneSnmpAgent</ApplicationTitle>
    <ApplicationId>com.SSG.snmpagent</ApplicationId>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
  </PropertyGroup>

  <ItemGroup>
    <MauiIcon Include="Resources\AppIcon\appicon.png" />
    <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />
    <MauiImage Include="Resources\Images\*" />
    <MauiFont Include="Resources\Fonts\*" />
    <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.50" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.5" />
    <PackageReference Include="SnmpSharpNet" Version="0.9.7" />
  </ItemGroup>
</Project>